matchBlocks=immersive_weathering:vitrified_sand end_stone \
netherrack blackstone create:veridium create:scorchia \
create:scoria create:ochrum create:limestone create:crimsite create:asurine \
arts_and_crafts:white_chalk immersive_weathering:permafrost spelunkery:nephrite \
smooth_basalt quark:shale quark:jasper quark:limestone dripstone_block \
tuff calcite andesite diorite \
granite deepslate stone quark:myalite \
sandstone red_sandstone biomesoplenty:white_sandstone \
biomesoplenty:orange_sandstone biomesoplenty:black_sandstone quark:soul_sandstone \
yungscavebiomes:ancient_sandstone yungscavebiomes:brittle_red_sandstone yungscavebiomes:brittle_sandstone \
amethyst_block galosphere:allurite_block galosphere:lumiere_block crying_obsidian \
obsidian magma_block glowstone \
galosphere:pink_salt galosphere:rose_pink_salt galosphere:pastel_pink_salt farmland \
immersive_weathering:loamy_farmland immersive_weathering:earthen_clay_farmland immersive_weathering:sandy_farmland \
immersive_weathering:silty_farmland ice packed_ice blue_ice \
ecologics:thin_ice yungscavebiomes:rare_ice wan_ancient_beasts:suspicious_ice \
terracotta white_terracotta light_gray_terracotta \
gray_terracotta black_terracotta brown_terracotta \
red_terracotta orange_terracotta yellow_terracotta \
lime_terracotta green_terracotta cyan_terracotta \
light_blue_terracotta blue_terracotta purple_terracotta \
magenta_terracotta pink_terracotta \
sandstone red_sandstone biomesoplenty:white_sandstone \
biomesoplenty:orange_sandstone biomesoplenty:black_sandstone quark:soul_sandstone \
yungscavebiomes:ancient_sandstone yungscavebiomes:brittle_red_sandstone yungscavebiomes:brittle_sandstone \
amethyst_block galosphere:allurite_block galosphere:lumiere_block crying_obsidian \
obsidian magma_block glowstone \
galosphere:pink_salt galosphere:rose_pink_salt galosphere:pastel_pink_salt farmland \
immersive_weathering:loamy_farmland immersive_weathering:earthen_clay_farmland immersive_weathering:sandy_farmland \
immersive_weathering:silty_farmland ice packed_ice blue_ice \
ecologics:thin_ice yungscavebiomes:rare_ice wan_ancient_beasts:suspicious_ice \
terracotta white_terracotta light_gray_terracotta \
gray_terracotta black_terracotta brown_terracotta \
red_terracotta orange_terracotta yellow_terracotta \
lime_terracotta green_terracotta cyan_terracotta \
light_blue_terracotta blue_terracotta purple_terracotta \
magenta_terracotta pink_terracotta
method=overlay
tiles=0-16
faces=all
connect=block
connectBlocks=deepslate_iron_ore
layer=cutouts