name = "pssycraft"
author = "me and my friend"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4e21968dfb77fc31ff1f764bad971c36d988f70c873cb7e10bfc9a97b931170"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
