name = "pssycraft"
author = "me and my friend"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87a3d5f945d016c1cfc2f43e19ad8f36d4849e5009e4d405d1578b8b73aa8489"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
