name = "pssycraft"
author = "me and my friend"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdf2b69d7ad27ddefbd164892c163025abf9e64295497ab81d7faab33f4650e6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
