matchBlocks= hearth_and_home:cyan_terracotta_bricks hearth_and_home:purple_terracotta_bricks hearth_and_home:blue_terracotta_bricks \
hearth_and_home:brown_terracotta_bricks hearth_and_home:green_terracotta_bricks hearth_and_home:red_terracotta_bricks \
hearth_and_home:black_terracotta_bricks vanillabackport:resin_bricks
method=overlay
tiles=0-16
faces=all
connectBlocks=hearth_and_home:cyan_terracotta_bricks