
[Display]
	#Горизонтальное смещение показателя выносливости (в пикселях).
	#Range: -1024 ~ 1024
	"Stamina X Offset" = -1
	#Вертикальное смещение показателя выносливости (в пикселях).
	#Range: -1024 ~ 1024
	"Stamina Y Offset" = -2

[Input]
	#Позволяет выполнять перекат двойным нажатием клавиши движения вместо отдельной кнопки.
	"Double Tap Mode" = false
	#Максимальный интервал (в миллисекундах) между двумя нажатиями, чтобы они засчитались как двойное.
	#Range: 0 ~ 1000
	"Double Tap Timeout" = 200

