
[Stamina]
	#Количество тиков с момента последней траты выносливости, в течение которых её регенерация подавляется.
	#По умолчанию 60 тиков (3 секунды)
	#Range: 0 ~ 6000
	"Regen Delay" = 60
	#Базовый интервал между восстановлением выносливости в тиках.
	#По умолчанию 20 тиков (1 секунда)
	#Range: 1 ~ 6000
	"Regen Interval" = 20
	#Сколько тиков срезается с интервала восстановления за каждую единицу атрибута регенерации выносливости.
	#По умолчанию 2
	#Range: 0 ~ 20
	"Regen Interval Reduction Per Attribute" = 2
	#Минимально допустимый интервал восстановления выносливости в тиках.
	#Интервал не может быть снижен ниже этого значения.
	#По умолчанию 5 тиков (0.25 секунды)
	#Range: 0 ~ 6000
	"Regen Interval Min" = 5

[Weight]
	#Запрещать ли сон в броне (кроме #soulslike:pajamas).
	#true – сон в броне запрещён.
	#false – спать можно независимо от веса.
	"Affect Sleeping" = true
	#Влияет ли тяжесть на давление воды.
	#true – тяжесть влияет на погружение.
	#false – вес не влияет на поведение в воде.
	"Affect Swimming" = true
	#Влияет ли тяжесть на максимальную выносливость игрока.
	#true – чем больше вес, тем меньше запас доступной выносливости.
	#false – выносливость не зависит от веса.
	"Affect Stamina" = true
	#Количество веса, добавляемое за каждую единицу брони.
	#Используется как базовый коэффициент веса от экипировки.
	#По умолчанию 0.5
	#Range: 0.0 ~ 100.0
	"Weight Per Armor" = 1.0
	#Количество скорости передвижения, вычитаемое за каждую единицу веса.
	#Используется как базовый коэффициент замедления от веса.
	#По умолчанию 0.02
	#Range: 0.0 ~ 10.0
	"Speed Per Weight" = 0.02
	#Переопределение веса конкретных предметов.
	#Формат: <item_id>=<weight>
	#Пример: minecraft:diamond_chestplate=3.0
	"Weight Overrides" = []
	#Множитель веса для чар Weightless.
	#По умолчанию 0.5 (50% тяжести)
	#Range: 0.0 ~ 10.0
	"Weightless Multiplier" = 0.5
	#Множитель веса для проклятия Weight Curse.
	#По умолчанию 2.0 (200% тяжести)
	#Range: 0.0 ~ 10.0
	"Weight Curse Multiplier" = 2.0
	#Сила давления воды за каждую единицу веса.
	#Работает только вне режима плавания.
	#По умолчанию 0.002
	#Range: 0.0 ~ 1.0
	"Water Push Per Weight" = 0.002
	#Количество скорости плавания, вычитаемое за каждую единицу веса.
	#Работает только в режиме плавания.
	#По умолчанию 0.01
	#Range: 0.0 ~ 1.0
	"Swim Speed Per Weight" = 0.007
	#Множитель вычитаемой скорости при активном эффекте Грации дельфина.
	#1.0 – грация не влияет на замедление от веса.
	#0.0 – грация полностью поглощает замедление от веса.
	#По умолчанию 0.5 (50% замедления сохраняется)
	#Range: 0.0 ~ 1.0
	"Dolphin Grace Multiplier" = 0.5
	#Общий множитель веса существ не-игроков
	#По умолчанию 1.0 (100% тяжести)
	#Range: 0.0 ~ 10.0
	"Non-Player Multiplier" = 0.7
	#Множители веса конкретных существ (перекрывают общий множитель).
	#1.0 – множитель по умолчанию, 100% веса.
	#0.0 – минимальный множитель, 0% веса (полностью поглощается).
	#Формат: <entity_id>=<weight>
	#Пример: minecraft:zombie=0.5
	"Entity Multipliers" = ["minecraft:skeleton=0.5", "royalvariations:fallen_royal_guard=0.3", "rottencreatures:immortal=0.3"]

[Dodge]
	#Перезарядка переката в тиках после его окончания.
	#Пока таймер перезарядки не истёк, игрок не может совершить новый перекат.
	#По умолчанию 20 тиков (1 секунда)
	#Range: 0 ~ 200
	"Dodge Cooldown" = 20
	#Стоимость переката в единицах выносливости.
	#Игрок не сможет совершить перекат, если его выносливость меньше этого значения.
	#По умолчанию 2 (целое пёрышко)
	#Range: 0 ~ 200
	"Dodge Cost" = 2
	#Скорость переката при максимальном весе игрока.
	#Чем меньше это значение, тем дольше длится перекат.
	#Скорость 1.0 соответствует 12 тикам длительности переката.
	#По умолчанию 0.75 (16 тиков)
	#Range: 0.2 ~ 5.0
	"Min Dodge Speed" = 0.75
	#Скорость переката при минимальном весе игрока.
	#Чем больше это значение, тем быстрее происходит перекат.
	#Скорость 1.0 соответствует 12 тикам длительности переката.
	#По умолчанию 1.25 (9.6 тиков)
	#Range: 0.2 ~ 5.0
	"Max Dodge Speed" = 1.25
	#Сила импульса переката при максимальном весе игрока.
	#Чем меньше это значение, тем меньше дистанция переката.
	#По умолчанию 0.75
	#Range: 0.0 ~ 10.0
	"Min Dodge Power" = 0.4
	#Сила импульса переката при минимальном весе игрока.
	#Чем больше это значение, тем больше дистанция переката.
	#По умолчанию 2.0
	#Range: 0.0 ~ 10.0
	"Max Dodge Power" = 0.6
	#Вес, при котором перекат достигает минимальной силы и скорости.
	#Если вес игрока равен или превышает это значение – используется Min Dodge Power и Min Dodge Speed.
	#По умолчанию 10.0
	#Range: 0.0 ~ 100.0
	"Max Dodge Weight" = 10.0
	#Вес, при котором перекат достигает максимальной силы и скорости.
	#Если вес игрока равен или ниже этого значения – используется Max Dodge Power и Max Dodge Speed.
	#По умолчанию 0.0
	#Range: 0.0 ~ 100.0
	"Min Dodge Weight" = 0.0
	#Положение центра окна неуязвимости относительно прогресса переката (0.0 – начало, 1.0 – конец).
	#По умолчанию 0.4
	#Range: 0.0 ~ 1.0
	"IFrame Center" = 0.5
	#Размер окна неуязвимости в тиках (целое число).
	#Например: значение 8 означает, что в центре переката будет 8 тиков неуязвимости.
	#Чем выше скорость переката, тем быстрее будет достигнуто начало окна.
	#По умолчанию 10 тиков
	#Range: 0 ~ 200
	"IFrame Window" = 8
	#Высота хитбокса игрока во время переката.
	#Меньшее значение позволяет игроку проскальзывать под низкими препятствиями.
	#По умолчанию 1.0 (один блок)
	#Range: 0.1 ~ 2.0
	"Dodge Height" = 1.0
	#Высота глаз игрока во время переката.
	#Определяет положение камеры и точку зрения игрока.
	#По умолчанию 0.8
	#Range: 0.0 ~ 2.0
	"Dodge Eye Height" = 0.8
	#Минимальный уровень сытости, требуемый для переката.
	#Если уровень сытости МЕНЬШЕ или РАВЕН этому значению – перекат невозможен.
	#1 единица сытости = половина окорочка.
	#По умолчанию 6 (3 окорочка)
	#Range: 0 ~ 20
	"Min Dodge Food Level" = 6

