#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 14 11:32:23 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=FreshEdit-2.0-RTX-DEFAULT-RethVoxels-r0.1-beta9 + Clrwl_1.0.3
enableShaders=true
