# Use Cloth Config mod for the descriptions.
---
snowGravity: true
snowMakingIce: false
snowAlwaysReplaceable: true
thinnerBoundingBox: false
snowNeverMelt: false
snowSpawnMaxLightLevel: 9
snowPersistMaxLightLevel: 11
snowReduceFallDamage: true
sustainGrassIfLayerMoreThanOne: true
fancySnowOnUpperSlab: true
mobSpawningMaxLayers: 8
snow-cover:
  replaceWorldgenFeature: true
  placeSnowOnBlock: true
  retainOriginalBlocks: false
  placeNaturally: true
accumulation:
  naturalMelting: true
  snowAndIceMeltInWarmBiomes: false
  maxLayers: 7
  accumulatesDuringSnowstorm: true
  accumulatesDuringSnowfall: true
integration:
  accumulationWinterOnly: false
debug:
  weatherTickSlowness: 16
  preventWorldgenLogSpam: true
  mobSpawningCommand: false
  skipSnowLoggingMushroom: true
