matchBlocks= unusualend:gloopslate_bricks \
cataclysm:azure_seastone_bricks quark:calcite_bricks spelunkery:rock_salt_bricks quark:myalite_bricks
method=overlay
tiles=0-16
faces=all
connectBlocks=unusualend:gloopslate_bricks
layer=cutout