matchBlocks= endergetic:cracked_end_stone_bricks quartz_bricks \
quark:granite_bricks quark:andesite_bricks quark:diorite_bricks quark:andesite_bricks \
quark:limestone_bricks quark:jasper_bricks quark:shale_bricks create:cut_granite_bricks \
create:cut_granite_bricks create:cut_diorite_bricks create:cut_andesite_bricks create:cut_calcite_bricks \
create:cut_dripstone_bricks create:cut_deepslate_bricks create:cut_tuff_bricks create:cut_asurine_bricks \
create:cut_crimsite_bricks create:cut_limestone_bricks create:cut_ochrum_bricks create:cut_scoria_bricks \
create:cut_scorchia_bricks create:cut_veridium_bricks unusualend:shiny_crystal_bricks unusualend:gloopslate_bricks \
cataclysm:azure_seastone_bricks quark:calcite_bricks spelunkery:rock_salt_bricks quark:myalite_bricks
method=overlay
tiles=0-16
faces=all
connectBlocks=endergetic:cracked_end_stone_bricks
layer=cutout