matchBlocks= cataclysm:azure_seastone_bricks quark:calcite_bricks spelunkery:rock_salt_bricks quark:myalite_bricks
method=overlay
tiles=0-16
faces=all
connectBlocks=cataclysm:azure_seastone_bricks
layer=cutout