matchBlocks= create:cut_limestone_bricks create:cut_ochrum_bricks create:cut_scoria_bricks \
create:cut_scorchia_bricks create:cut_veridium_bricks unusualend:shiny_crystal_bricks unusualend:gloopslate_bricks \
cataclysm:azure_seastone_bricks quark:calcite_bricks spelunkery:rock_salt_bricks quark:myalite_bricks
method=overlay
tiles=0-16
faces=all
connectBlocks=create:cut_limestone_bricks
layer=cutout