matchBlocks=ecologics:coconut_planks ecologics:walnut_planks \
ecologics:azalea_planks ecologics:flowering_azalea_planks autumnity:maple_planks \
immersive_weathering:charred_planks vanillabackport:pale_oak_planks atmospheric:rosewood_planks \
atmospheric:morado_planks atmospheric:yucca_planks atmospheric:laurel_planks atmospheric:aspen_planks \
atmospheric:kousa_planks atmospheric:grimwood_planks phantasm:pream_planks endergetic:poise_planks \
unusualend:chorus_nest_planks cataclysm:chorus_planksmethod=overlaymethod=overlaymethod=overlay
method=overlay
tiles=0-16
faces=all
connectBlocks=ecologics:coconut_planks
layer=cutout